version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - 5430:5432
    #    volumes:
    #      - ./postgres-data:/var/lib/postgresql/data
    network_mode: "bridge"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
